// Generated by scripts/generate-avatars.mjs — do not edit.
export const AVATAR_IDS = [
  "peeps-01",
  "peeps-02",
  "peeps-03",
  "peeps-04",
  "peeps-05",
  "peeps-06",
  "pixel-01",
  "pixel-02",
  "pixel-03",
  "pixel-04",
  "pixel-05",
  "pixel-06",
  "lorelei-01",
  "lorelei-02",
  "lorelei-03",
  "lorelei-04",
  "lorelei-05",
  "lorelei-06",
  "thumbs-01",
  "thumbs-02",
  "thumbs-03",
  "thumbs-04",
  "thumbs-05",
  "thumbs-06",
] as const;

export type AvatarId = (typeof AVATAR_IDS)[number];
